"""add video views analytics

Revision ID: 20cd0e644767
Revises: c04b3db9d086
Create Date: 2026-01-29 16:01:03.472926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20cd0e644767'
down_revision: Union[str, Sequence[str], None] = 'c04b3db9d086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('watch_seconds', sa.Integer(), nullable=True),
    sa.Column('last_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_views_id'), 'video_views', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_views_id'), table_name='video_views')
    op.drop_table('video_views')
    # ### end Alembic commands ###
