"""add hls_path to videos

Revision ID: c04b3db9d086
Revises: 3efad87ffd02
Create Date: 2026-01-29 12:53:45.299588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04b3db9d086'
down_revision: Union[str, Sequence[str], None] = '3efad87ffd02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('hls_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'hls_path')
    # ### end Alembic commands ###
